name: i_am_rich
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  http: ^0.13.4

  lottie: ^1.2.2
  flutter_hooks: ^0.18.2+1
  provider_architecture: ^1.1.1+1
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_analytics: ^9.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.1.2


flutter:
  uses-material-design: true
  assets:
    - images/
    - anis/
    - assets/
  fonts:
    - family: Devanagari
      fonts:
        - asset: fonts/shree.ttf

flutter_native_splash:
  background_image: images/pdosSplash.png

